### ISSUE TITLE
All promises rejected error

### ISSUE THREAD

**Issue by derfredy** [eco-stake/restake#299]
Hi mates,
My restake was working nicely for cosmoshub until today. I just pulled repo changes and rebuilt as usually.
What info would help to debug this?

This are the logs:

```
/usr/local/bin/docker-compose run --rm app npm run autostake cosmoshub
Creating restake_app_run ... done

> restake@0.1.0 autostake
> node scripts/autostake.mjs "cosmoshub"

[11:59:47.011] Cosmos Hub bot address is cosmos1dg8u5qll7fjm9nnwqns0ullhtc6g552ugd0eqj
[11:59:47.137] Failed to connect All promises were rejected
```

Before that it worked like this:

```
19-03-22/10:01:01
Creating restake_app_run ... 
Creating restake_app_run ... done

> restake@0.1.0 autostake
> node scripts/autostake.mjs "cosmoshub"

Cosmos Hub bot address is cosmos1dg8u5qll7fjm9nnwqns0ullhtc6g552ugd0eqj
Using REST URL http://127.0.0.1:1317
Using RPC URL http://127.0.0.1:26657
Running autostake
Bot balance is 72024 uatom
Finding delegators...
...batch 1
...batch 2
...batch 3
...batch 4
Checking 356 delegators for grants...
...batch 1
...batch 2
...batch 3
...batch 4
```

**Comment by tombeynon** [comment]
Are your nodes still up at `http://127.0.0.1` ? The error that early means it couldn't connect at all, even to check status

**Comment by derfredy** [comment]
Solved adding this to my docker-compose.json

   network_mode: "host"

It seems it was overwritten by the git pull.  This flag is needed by docker-compose when runing your node localy at 127.0.0.1

This is my modified docker-compose.json :

```
version: "3.3"

services:
  app:
    build: .
    network_mode: "host"
    env_file:
      - .env
    ports:
      - '1234:1234'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
```
